data: cifar10
device: cuda:0
batch_size: 50000
random_seed: 42
num_epochs: 20
optimizer1: adam
learning_rate1: 0.01
optimizer2: None
learning_rate2: null
lambd: null
lipschitz: null
momentum: 0.0
verbose: 1
